from collections import deque
from copy import deepcopy

import numpy as np
import torch
import torch.nn as nn

from onpolicy.utils.md_roster import (
    order_md_candidates,
    resolve_distance_only_user_sort,
)


class MDGRUPredictor(nn.Module):
    """One receiver-local mobility model whose parameters are shared by MD IDs."""

    def __init__(self, feature_dim, hidden_dim):
        super().__init__()
        self.gru = nn.GRUCell(feature_dim + 1, hidden_dim)
        self.head = nn.Sequential(
            nn.Linear(hidden_dim + 1, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, feature_dim),
        )

    def update(self, feature, age, hidden):
        return self.gru(torch.cat((feature, age), dim=-1), hidden)

    def predict(self, hidden, age):
        return self.head(torch.cat((hidden, age), dim=-1))


class _SequenceReplay:
    """Bounded receiver-local replay of raw observation histories."""

    def __init__(self, capacity, seed):
        self.items = deque(maxlen=int(capacity))
        self.rng = np.random.default_rng(seed)
        self.new_since_train = 0

    def add(self, history_inputs, prediction_age, target):
        history_inputs = np.asarray(history_inputs, dtype=np.float32)
        if history_inputs.ndim != 2 or not len(history_inputs):
            raise ValueError("MD-GRU replay requires a non-empty observation history")
        self.items.append((
            history_inputs.copy(),
            np.asarray(prediction_age, dtype=np.float32).copy(),
            np.asarray(target, dtype=np.float32).copy(),
        ))
        self.new_since_train += 1

    def sample(self, count):
        count = min(int(count), len(self.items))
        if count <= 0:
            return []
        indices = self.rng.choice(len(self.items), size=count, replace=False)
        items = list(self.items)
        return [items[int(index)] for index in indices]

    def age_counts(self, lifetime_scale):
        """Return natural supervision counts for ages 1, 2, 3, and 4+."""
        counts = np.zeros(4, dtype=np.int64)
        for _, normalized_age, _ in self.items:
            age = int(round(float(normalized_age[0]) * max(lifetime_scale, 1)))
            counts[min(max(age, 1), 4) - 1] += 1
        return counts

    def mark_trained(self):
        count = self.new_since_train
        self.new_since_train = 0
        return count


class _MemoryBank:
    def __init__(self, environments, capacity, feature_dim, hidden_dim, device):
        self.environments = environments
        self.capacity = capacity
        self.feature_dim = feature_dim
        self.hidden_dim = hidden_dim
        self.device = device
        self.ids = np.full((environments, capacity), -1, dtype=np.int64)
        self.age = np.zeros((environments, capacity), dtype=np.int32)
        self.lifetime = np.zeros((environments, capacity), dtype=np.int32)
        self.last_feature = np.zeros((environments, capacity, feature_dim), dtype=np.float32)
        self.estimate = np.zeros_like(self.last_feature)
        self.tasks = np.zeros((environments, capacity, 3), dtype=np.float32)
        self.task_valid = np.zeros((environments, capacity), dtype=bool)
        self.hidden = torch.zeros(
            environments, capacity, hidden_dim, device=device, dtype=torch.float32
        )
        # Raw received inputs are retained only for the current episode/session.
        # Replay copies these short histories, so training can recompute hidden
        # states with current parameters instead of backpropagating through stale
        # hidden tensors generated by an older predictor.
        self.histories = [
            [[] for _ in range(capacity)] for _ in range(environments)
        ]

    def reset(self, environment_mask=None):
        if environment_mask is None:
            environment_mask = np.ones(self.environments, dtype=bool)
        self.ids[environment_mask] = -1
        self.age[environment_mask] = 0
        self.lifetime[environment_mask] = 0
        self.last_feature[environment_mask] = 0
        self.estimate[environment_mask] = 0
        self.tasks[environment_mask] = 0
        self.task_valid[environment_mask] = False
        mask = torch.as_tensor(environment_mask, device=self.device)
        self.hidden[mask] = 0
        for environment in np.flatnonzero(environment_mask):
            for history in self.histories[int(environment)]:
                history.clear()

    def find(self, environment, session_id):
        matches = np.flatnonzero(self.ids[environment] == session_id)
        return int(matches[0]) if len(matches) else None

    def allocate(self, environment, session_id):
        free = np.flatnonzero(self.ids[environment] == -1)
        if not len(free):
            raise RuntimeError("MD memory capacity was exceeded")
        slot = int(free[0])
        self.ids[environment, slot] = session_id
        self.age[environment, slot] = 0
        self.lifetime[environment, slot] = 0
        self.hidden[environment, slot] = 0
        self.histories[environment][slot].clear()
        return slot

    def remove_expired(self, environment, protected_ids=()):
        expired = (self.ids[environment] != -1) & (self.lifetime[environment] <= 0)
        if protected_ids:
            expired &= ~np.isin(self.ids[environment], list(protected_ids))
        if not np.any(expired):
            return
        self.ids[environment, expired] = -1
        self.age[environment, expired] = 0
        self.lifetime[environment, expired] = 0
        self.last_feature[environment, expired] = 0
        self.estimate[environment, expired] = 0
        self.tasks[environment, expired] = 0
        self.task_valid[environment, expired] = False
        mask = torch.as_tensor(expired, device=self.device)
        self.hidden[environment, mask] = 0
        for slot in np.flatnonzero(expired):
            self.histories[environment][int(slot)].clear()


class MDStateReconstructor:
    """Causal receiver-ID memory and optional MD-GRU Type-S reconstruction."""

    feature_dim = 7  # x, y, speed, sin/cos(direction), sin/cos(reference direction)

    def __init__(self, args, device):
        self.args = args
        self.device = device
        self.mode = args.state_reconstruction
        self.n_uavs = args.n_UAVs
        self.capacity = args.n_GUs
        self.packet_capacity = args.max_GUs_in_range
        self.hidden_dim = args.md_gru_hidden_dim
        self.train_samples = int(getattr(args, "md_gru_train_samples", 512))
        self.min_ready_samples = int(
            getattr(args, "md_gru_min_ready_samples", 512)
        )
        if self.mode == "md_gru":
            if self.hidden_dim <= 0 or args.md_gru_max_samples <= 0:
                raise ValueError("md_gru_hidden_dim and md_gru_max_samples must be positive")
            if args.md_gru_lr <= 0 or args.md_gru_epochs <= 0 or args.md_gru_batch_size <= 0:
                raise ValueError(
                    "md_gru_lr, md_gru_epochs, and md_gru_batch_size must be positive"
                )
            if self.train_samples <= 0:
                raise ValueError("md_gru_train_samples must be positive")
            if not 0 < self.min_ready_samples <= args.md_gru_max_samples:
                raise ValueError(
                    "md_gru_min_ready_samples must be in [1, md_gru_max_samples]"
                )
        self.distance_only_user_sort = resolve_distance_only_user_sort(args)
        self.metadata = bool(getattr(args, "critic_md_metadata", False) or self.mode != "zero")
        predictor_template = (
            MDGRUPredictor(self.feature_dim, self.hidden_dim).to(device)
            if self.mode == "md_gru" else None
        )
        # Identical initialization is a fair shared prior; optimizers and all
        # subsequent receiver data/updates remain strictly local.
        self.predictors = (
            nn.ModuleList([deepcopy(predictor_template) for _ in range(self.n_uavs)])
            if predictor_template is not None else None
        )
        self.optimizers = (
            [
                torch.optim.Adam(predictor.parameters(), lr=args.md_gru_lr)
                for predictor in self.predictors
            ]
            if self.predictors is not None else None
        )
        self.replays = (
            [
                _SequenceReplay(args.md_gru_max_samples, args.seed + 7919 + receiver)
                for receiver in range(self.n_uavs)
            ]
            if self.predictors is not None else None
        )
        self.training_rng = np.random.default_rng(args.seed + 15485863)
        # Do not expose a randomly initialized mobility head to the critic.
        # The last observed persistent record is used until receiver-local
        # replay reaches the configured warm-up and one update completes.
        self.predictor_ready = (
            [False for _ in range(self.n_uavs)]
            if self.predictors is not None else [True for _ in range(self.n_uavs)]
        )
        self.banks = None
        self.environments = None
        self.last_data = None
        self.query_age_counts = np.zeros((self.n_uavs, 4), dtype=np.int64)
        self.prequential_prediction_sse = np.zeros(self.n_uavs, dtype=np.float64)
        self.prequential_last_obs_sse = np.zeros(self.n_uavs, dtype=np.float64)
        self.prequential_sample_count = np.zeros(self.n_uavs, dtype=np.int64)
        self._collect_metrics = False

    def checkpoint_state(self):
        """Return receiver-local trainable state (the replay cache is transient)."""
        if self.predictors is None:
            raise RuntimeError("only md_gru reconstruction has predictor state")
        return {
            "models": self.predictors.state_dict(),
            "optimizers": [optimizer.state_dict() for optimizer in self.optimizers],
            "predictor_ready": list(self.predictor_ready),
        }

    def load_checkpoint_state(self, checkpoint):
        """Load current checkpoints and the legacy model-only representation."""
        if self.predictors is None:
            raise RuntimeError("only md_gru reconstruction has predictor state")
        if isinstance(checkpoint, dict) and "models" in checkpoint:
            self.predictors.load_state_dict(checkpoint["models"])
            for optimizer, optimizer_state in zip(
                self.optimizers, checkpoint.get("optimizers", ())
            ):
                optimizer.load_state_dict(optimizer_state)
            ready = checkpoint.get("predictor_ready", [True] * self.n_uavs)
            self.predictor_ready = [bool(value) for value in ready]
        else:
            # Legacy checkpoints contained one model shared across all UAVs.
            legacy_model = checkpoint.get("model", checkpoint)
            for predictor in self.predictors:
                predictor.load_state_dict(legacy_model)
            self.predictor_ready = [
                bool(checkpoint.get("predictor_ready", True))
                if isinstance(checkpoint, dict) else True
                for _ in range(self.n_uavs)
            ]
        self.predictors.eval()

    def _ensure_banks(self, environments):
        if self.banks is not None and self.environments == environments:
            return
        self.environments = environments
        self.banks = [
            _MemoryBank(
                environments, self.capacity, self.feature_dim,
                self.hidden_dim, self.device,
            )
            for _ in range(self.n_uavs)
        ]

    def reset(self, environment_mask=None):
        if self.banks is None:
            return
        for bank in self.banks:
            bank.reset(environment_mask)

    def _speed_bound(self):
        """Return the largest MD speed admitted by the configured environment."""
        candidates = [
            1.3 * float(self.args.mean_velocity),
            float(getattr(self.args, "md_velocity_init_max_factor", 1.3))
            * float(self.args.mean_velocity),
        ]
        update_clip_max = getattr(self.args, "md_velocity_update_clip_max", None)
        if update_clip_max is not None:
            candidates.append(float(update_clip_max))
        return max(*candidates, 1e-6)

    def _encode_feature(self, record):
        x_span = max(self.args.x_max_gu - self.args.x_min_gu, 1e-6)
        y_span = max(self.args.y_max_gu - self.args.y_min_gu, 1e-6)
        speed_bound = self._speed_bound()
        return np.asarray([
            2 * (record[0] - self.args.x_min_gu) / x_span - 1,
            2 * (record[1] - self.args.y_min_gu) / y_span - 1,
            2 * record[2] / speed_bound - 1,
            np.sin(record[3]), np.cos(record[3]),
            np.sin(record[4]), np.cos(record[4]),
        ], dtype=np.float32)

    def _decode_feature(self, feature):
        feature = np.asarray(feature, dtype=np.float64)
        x_span = max(self.args.x_max_gu - self.args.x_min_gu, 1e-6)
        y_span = max(self.args.y_max_gu - self.args.y_min_gu, 1e-6)
        speed_bound = self._speed_bound()
        x = self.args.x_min_gu + 0.5 * (np.clip(feature[0], -1, 1) + 1) * x_span
        y = self.args.y_min_gu + 0.5 * (np.clip(feature[1], -1, 1) + 1) * y_span
        speed = 0.5 * (np.clip(feature[2], -1, 1) + 1) * speed_bound
        direction = np.arctan2(feature[3], feature[4]) % (2 * np.pi)
        reference = np.arctan2(feature[5], feature[6]) % (2 * np.pi)
        return np.asarray((x, y, speed, direction, reference), dtype=np.float64)

    def _age_feature(self, age):
        return np.asarray([age / max(self.args.md_lifetime_max, 1)], dtype=np.float32)

    @staticmethod
    def _observed_records(data, environment, receiver):
        observed = {}
        n_uavs = data["record_features"].shape[1]
        sources = [receiver] + [
            sender for sender in range(n_uavs)
            if sender != receiver
            and data["geometric_mask"][environment, receiver, sender]
            and data["reception_mask"][environment, receiver, sender]
        ]
        for sender in sources:
            valid_slots = np.flatnonzero(data["record_valid"][environment, sender])
            for slot in valid_slots:
                session_id = int(data["session_ids"][environment, sender, slot])
                record = data["record_features"][environment, sender, slot]
                if session_id in observed:
                    common = np.r_[record[:6], record[7:10]]
                    previous = np.r_[observed[session_id][:6], observed[session_id][7:10]]
                    if not np.allclose(common, previous, rtol=1e-6, atol=1e-6):
                        raise AssertionError("duplicate MD records disagree across Type-S sources")
                    continue
                observed[session_id] = record
        return observed

    @torch.no_grad()
    def _update_bank(self, receiver, data, collect_samples):
        bank = self.banks[receiver]
        predictor = self.predictors[receiver] if self.predictors is not None else None
        observed_by_environment = [
            self._observed_records(data, environment, receiver)
            for environment in range(self.environments)
        ]

        # Advance all active identities in one vectorized pass. In MD-GRU mode
        # this is one prediction call per receiver, rather than one tiny GPU
        # kernel per environment/session pair.
        bank.task_valid[:] = False
        active = bank.ids != -1
        bank.age[active] += 1
        bank.lifetime[active] -= 1
        for environment in range(self.environments):
            bank.remove_expired(
                environment, protected_ids=set(observed_by_environment[environment])
            )
        active = bank.ids != -1
        active_environments, active_slots = np.nonzero(active)
        if len(active_slots):
            if predictor is None or not self.predictor_ready[receiver]:
                bank.estimate[active_environments, active_slots] = bank.last_feature[
                    active_environments, active_slots
                ]
            else:
                active_environment_index = torch.as_tensor(
                    active_environments, device=self.device, dtype=torch.long
                )
                active_slot_index = torch.as_tensor(
                    active_slots, device=self.device, dtype=torch.long
                )
                age = torch.as_tensor(
                    bank.age[active_environments, active_slots, None]
                    / max(self.args.md_lifetime_max, 1),
                    device=self.device, dtype=torch.float32,
                )
                prediction = predictor.predict(
                    bank.hidden[active_environment_index, active_slot_index], age
                )
                bank.estimate[active_environments, active_slots] = (
                    prediction.cpu().numpy()
                )

        update_environments = []
        update_slots = []
        update_features = []
        update_ages = []
        for environment in range(self.environments):
            observed = observed_by_environment[environment]
            for session_id, record in observed.items():
                feature = self._encode_feature(record)
                slot = bank.find(environment, session_id)
                is_new = slot is None
                if is_new:
                    slot = bank.allocate(environment, session_id)
                    update_age = 0
                else:
                    update_age = int(bank.age[environment, slot])
                    if predictor is not None and collect_samples:
                        if self.predictor_ready[receiver]:
                            x_scale = 0.5 * max(
                                self.args.x_max_gu - self.args.x_min_gu, 1e-6
                            )
                            y_scale = 0.5 * max(
                                self.args.y_max_gu - self.args.y_min_gu, 1e-6
                            )
                            prediction_error = (
                                bank.estimate[environment, slot, :2] - feature[:2]
                            ) * np.asarray((x_scale, y_scale))
                            last_obs_error = (
                                bank.last_feature[environment, slot, :2] - feature[:2]
                            ) * np.asarray((x_scale, y_scale))
                            self.prequential_prediction_sse[receiver] += float(
                                np.dot(prediction_error, prediction_error)
                            )
                            self.prequential_last_obs_sse[receiver] += float(
                                np.dot(last_obs_error, last_obs_error)
                            )
                            self.prequential_sample_count[receiver] += 1
                        self.replays[receiver].add(
                            bank.histories[environment][slot],
                            self._age_feature(update_age),
                            feature,
                        )
                update_environments.append(environment)
                update_slots.append(slot)
                update_features.append(feature)
                update_ages.append(update_age)
                bank.last_feature[environment, slot] = feature
                bank.estimate[environment, slot] = feature
                bank.age[environment, slot] = 0
                bank.lifetime[environment, slot] = int(round(record[5]))
                bank.tasks[environment, slot] = record[7:10]
                bank.task_valid[environment, slot] = True

        if update_slots:
            update_environments = np.asarray(update_environments, dtype=np.int64)
            update_slots = np.asarray(update_slots, dtype=np.int64)
            update_features = np.asarray(update_features, dtype=np.float32)
            normalized_ages = np.asarray(
                [self._age_feature(age) for age in update_ages], dtype=np.float32
            )
            feature_tensor = torch.as_tensor(
                update_features, device=self.device, dtype=torch.float32
            )
            age_tensor = torch.as_tensor(
                normalized_ages, device=self.device, dtype=torch.float32
            )
            update_input = torch.cat((feature_tensor, age_tensor), dim=-1)
            update_environment_index = torch.as_tensor(
                update_environments, device=self.device, dtype=torch.long
            )
            update_slot_index = torch.as_tensor(
                update_slots, device=self.device, dtype=torch.long
            )
            old_hidden = bank.hidden[
                update_environment_index, update_slot_index
            ].clone()
            if predictor is not None:
                bank.hidden[
                    update_environment_index, update_slot_index
                ] = predictor.gru(update_input, old_hidden)
            for environment, slot, raw_input in zip(
                update_environments, update_slots, update_input.cpu().numpy()
            ):
                bank.histories[int(environment)][int(slot)].append(raw_input.copy())

    def _channel_gain(self, sender_position, md_position):
        horizontal = np.linalg.norm(sender_position - md_position)
        vertical = self.args.H_UAV - self.args.H_GU
        distance = max(np.hypot(horizontal, vertical), 1e-10)
        theta = 180 / np.pi * np.arcsin(np.clip(vertical / distance, -1, 1))
        p_los = 1 / (1 + 9.61 * np.exp(-0.16 * (theta - 9.61)))
        log_term = 20 * np.log10(4 * np.pi * 2e9 / 3e8)
        path_loss = (
            p_los * (log_term + 1 + 20 * np.log10(distance))
            + (1 - p_los) * (log_term + 20 + 20 * np.log10(distance))
        )
        return 10 ** (-path_loss / 10)

    def _direct_block(self, data, environment, sender):
        pieces = [
            data["critic_prefix"][environment, sender],
            data["record_features"][environment, sender].reshape(-1),
        ]
        if self.metadata:
            valid = data["record_valid"][environment, sender].astype(np.float64)
            metadata = np.stack((valid, valid, np.zeros_like(valid)), axis=-1)
            pieces.append(metadata.reshape(-1))
        return np.concatenate(pieces)

    def _surrogate_prefix(
        self, data, environment, receiver, sender, visible_count
    ):
        values = []
        if self.args.ob_state_with_timestep:
            # Time is locally known even when the sender packet is lost.
            values.append(data["critic_prefix"][environment, receiver, :1])
        if self.args.ob_state_with_id:
            identity = np.zeros(self.n_uavs, dtype=np.float64)
            identity[sender] = 1
            values.append(identity)
        values.append(data["uav_positions"][environment, sender, :2])
        layout_dim = 8 if getattr(self.args, "episode_layout_context", False) else 0
        if layout_dim:
            layout_start = (
                int(self.args.ob_state_with_timestep)
                + (self.n_uavs if self.args.ob_state_with_id else 0)
                + 2
            )
            values.append(data["critic_prefix"][
                environment, receiver, layout_start:layout_start + layout_dim
            ])
        values.append(np.asarray([visible_count], dtype=np.float64))
        return np.concatenate(values)

    def _surrogate_block(self, data, environment, receiver, sender):
        bank = self.banks[receiver]
        slots = np.flatnonzero(bank.ids[environment] != -1)
        sender_position = data["uav_positions"][environment, sender, :2]
        candidates = []
        for slot in slots:
            decoded = self._decode_feature(bank.estimate[environment, slot])
            distance = float(np.linalg.norm(decoded[:2] - sender_position))
            if distance > self.args.Cover_R:
                continue
            task_valid = bool(bank.task_valid[environment, slot])
            if task_valid:
                task = bank.tasks[environment, slot]
                can_finish = task[1] / self.args.F_n <= task[2]
            else:
                can_finish = False
            candidates.append((
                distance, int(bank.ids[environment, slot]), slot, decoded,
                task_valid, can_finish,
            ))
        if candidates:
            order = order_md_candidates(
                [item[0] for item in candidates],
                [item[1] for item in candidates],
                [item[5] for item in candidates],
                [item[4] for item in candidates],
                distance_only=self.distance_only_user_sort,
            )
            candidates = [candidates[index] for index in order]
        visible_count = len(candidates)
        records = np.zeros((self.packet_capacity, 10), dtype=np.float64)
        metadata = np.zeros((self.packet_capacity, 3), dtype=np.float64)
        placeholder = np.asarray([
            0.5 * (self.args.D_min + self.args.D_max),
            0.5 * (self.args.C_min + self.args.C_max),
            0.5 * (self.args.delay_min + self.args.delay_max),
        ])
        for record_slot, (_, _, memory_slot, decoded, _, _) in enumerate(
            candidates[:self.packet_capacity]
        ):
            if self._collect_metrics:
                age = int(bank.age[environment, memory_slot])
                self.query_age_counts[receiver, min(max(age, 1), 4) - 1] += 1
            records[record_slot, :5] = decoded
            records[record_slot, 5] = bank.lifetime[environment, memory_slot]
            records[record_slot, 6] = self._channel_gain(sender_position, decoded[:2])
            task_valid = bool(bank.task_valid[environment, memory_slot])
            records[record_slot, 7:10] = (
                bank.tasks[environment, memory_slot] if task_valid else placeholder
            )
            metadata[record_slot] = (
                1.0,
                float(task_valid),
                bank.age[environment, memory_slot] / max(self.args.md_lifetime_max, 1),
            )
        pieces = [
            self._surrogate_prefix(
                data, environment, receiver, sender, visible_count
            ),
            records.reshape(-1),
        ]
        if self.metadata:
            pieces.append(metadata.reshape(-1))
        return np.concatenate(pieces)

    def reconstruct(self, data, reset_environments=None, collect_samples=True):
        environments = data["record_features"].shape[0]
        self._ensure_banks(environments)
        if reset_environments is not None:
            self.reset(np.asarray(reset_environments, dtype=bool))
        self.last_data = data
        self._collect_metrics = bool(collect_samples)
        for receiver in range(self.n_uavs):
            self._update_bank(receiver, data, collect_samples)

        block_dim = (
            data["critic_prefix"].shape[-1]
            + self.packet_capacity * 10
            + (self.packet_capacity * 3 if self.metadata else 0)
        )
        states = np.zeros(
            (environments, self.n_uavs, self.n_uavs * block_dim), dtype=np.float64
        )
        attention = np.zeros(
            (environments, self.n_uavs, self.n_uavs), dtype=np.float32
        )
        all_senders = np.arange(self.n_uavs)
        for environment in range(environments):
            for receiver in range(self.n_uavs):
                sender_order = np.concatenate((
                    [receiver], all_senders[all_senders != receiver]
                ))
                for block_slot, sender in enumerate(sender_order):
                    geometric = bool(data["geometric_mask"][environment, receiver, sender])
                    received = bool(data["reception_mask"][environment, receiver, sender])
                    if sender == receiver or (geometric and received):
                        block = self._direct_block(data, environment, sender)
                    elif geometric:
                        block = self._surrogate_block(
                            data, environment, receiver, sender
                        )
                    else:
                        continue
                    start = block_slot * block_dim
                    states[environment, receiver, start:start + block_dim] = block
                    attention[environment, receiver, block_slot] = 1
        return states, attention

    @staticmethod
    def _age_fraction_metrics(prefix, counts):
        total = int(np.sum(counts))
        denominator = max(total, 1)
        return {
            f"{prefix}_count": total,
            f"{prefix}_age1_fraction": float(counts[0] / denominator),
            f"{prefix}_age2_fraction": float(counts[1] / denominator),
            f"{prefix}_age3_fraction": float(counts[2] / denominator),
            f"{prefix}_age4plus_fraction": float(counts[3] / denominator),
        }

    def _prediction_diagnostics(self, receiver, replay):
        label_counts = replay.age_counts(self.args.md_lifetime_max)
        query_counts = self.query_age_counts[receiver].copy()
        prequential_count = int(self.prequential_sample_count[receiver])
        diagnostics = {
            **self._age_fraction_metrics("md_prediction_replay_label", label_counts),
            **self._age_fraction_metrics("md_prediction_rollout_query", query_counts),
            "md_prediction_prequential_samples": prequential_count,
            "md_prediction_prequential_rmse_m": float(np.sqrt(
                self.prequential_prediction_sse[receiver]
                / max(prequential_count, 1)
            )),
            "md_last_obs_prequential_rmse_m": float(np.sqrt(
                self.prequential_last_obs_sse[receiver]
                / max(prequential_count, 1)
            )),
        }
        self.query_age_counts[receiver] = 0
        self.prequential_prediction_sse[receiver] = 0.0
        self.prequential_last_obs_sse[receiver] = 0.0
        self.prequential_sample_count[receiver] = 0
        return diagnostics

    def train_predictors(self):
        x_scale = 0.5 * max(self.args.x_max_gu - self.args.x_min_gu, 1e-6)
        y_scale = 0.5 * max(self.args.y_max_gu - self.args.y_min_gu, 1e-6)
        metrics = []
        for receiver in range(self.n_uavs):
            replay = self.replays[receiver]
            new_samples = replay.mark_trained()
            replay_size = len(replay.items)
            diagnostics = self._prediction_diagnostics(receiver, replay)
            if replay_size < self.min_ready_samples or new_samples == 0:
                metrics.append({
                    "md_prediction_loss": 0.0,
                    "md_prediction_samples": new_samples,
                    "md_prediction_replay_size": replay_size,
                    "md_prediction_train_samples": 0,
                    "md_prediction_position_rmse_m": 0.0,
                    "md_prediction_age_mean": 0.0,
                    "md_prediction_age_ge2_fraction": 0.0,
                    **diagnostics,
                })
                continue
            samples = replay.sample(self.train_samples)

            predictor = self.predictors[receiver]
            optimizer = self.optimizers[receiver]
            predictor.train()
            epoch_losses = []
            position_squared_error = 0.0
            position_sample_count = 0
            ages = np.asarray([
                sample[1][0] * max(self.args.md_lifetime_max, 1)
                for sample in samples
            ])
            for epoch in range(self.args.md_gru_epochs):
                order = self.training_rng.permutation(len(samples))
                for start in range(0, len(samples), self.args.md_gru_batch_size):
                    batch = [samples[index] for index in order[
                        start:start + self.args.md_gru_batch_size
                    ]]
                    histories, prediction_ages, targets = zip(*batch)
                    lengths = np.asarray(
                        [len(history) for history in histories], dtype=np.int64
                    )
                    padded = np.zeros(
                        (
                            len(batch),
                            int(np.max(lengths)),
                            self.feature_dim + 1,
                        ),
                        dtype=np.float32,
                    )
                    for row, history in enumerate(histories):
                        padded[row, :len(history)] = history
                    history = torch.as_tensor(
                        padded, device=self.device, dtype=torch.float32
                    )
                    sequence_lengths = torch.as_tensor(
                        lengths, device=self.device, dtype=torch.long
                    )
                    hidden = torch.zeros(
                        len(batch), self.hidden_dim,
                        device=self.device, dtype=torch.float32,
                    )
                    for timestep in range(history.shape[1]):
                        updated = predictor.gru(history[:, timestep], hidden)
                        active = (sequence_lengths > timestep)[:, None]
                        hidden = torch.where(active, updated, hidden)
                    age = torch.as_tensor(
                        np.asarray(prediction_ages),
                        device=self.device,
                        dtype=torch.float32,
                    )
                    prediction = predictor.predict(hidden, age)
                    target = torch.as_tensor(
                        np.asarray(targets), device=self.device, dtype=torch.float32
                    )
                    # Smooth-L1 is less sensitive than MSE to boundary bounces
                    # and rare long-gap mobility outliers.
                    loss = nn.functional.smooth_l1_loss(prediction, target)
                    if epoch == self.args.md_gru_epochs - 1:
                        position_error = (
                            ((prediction[:, 0] - target[:, 0]) * x_scale) ** 2
                            + ((prediction[:, 1] - target[:, 1]) * y_scale) ** 2
                        )
                        position_squared_error += float(
                            torch.sum(position_error).detach().cpu()
                        )
                        position_sample_count += len(batch)
                    optimizer.zero_grad()
                    loss.backward()
                    nn.utils.clip_grad_norm_(predictor.parameters(), 1.0)
                    optimizer.step()
                    epoch_losses.append(float(loss.detach().cpu()))
            predictor.eval()
            self.predictor_ready[receiver] = True
            metrics.append({
                "md_prediction_loss": float(np.mean(epoch_losses)),
                "md_prediction_samples": new_samples,
                "md_prediction_replay_size": replay_size,
                "md_prediction_train_samples": len(samples),
                "md_prediction_position_rmse_m": float(np.sqrt(
                    position_squared_error / max(position_sample_count, 1)
                )),
                "md_prediction_age_mean": float(np.mean(ages)),
                "md_prediction_age_ge2_fraction": float(np.mean(ages >= 2.0)),
                **diagnostics,
            })
        return metrics
